version: '3'

services:
  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: otus/nginx
    container_name: webserver
    ports:
      - "8089:80"
    volumes:
      - ./app/:/var/www/html
    networks:
      - app-network
  
  app:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: otus/php
    container_name: app
    env_file: .env
    volumes:
      - ./app/:/var/www/html
    networks:
      - app-network

  db:
    image: public.ecr.aws/docker/library/mysql:8.0
    restart: always
    container_name: db
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        MYSQL_USER: '${MYSQL_USER}'
        MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
        - ./docker_data/:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - app-network
  
  adminer:
      image: public.ecr.aws/docker/library/adminer
      restart: always
      container_name: adminer
      depends_on:
          - db
      ports:
          - 8083:8080
      networks:
          - app-network

networks:
  app-network:
    driver: bridge